### ISSUE TITLE
plugin manipulating dom

### ISSUE THREAD

**Issue by celron** [wf9a5m75/phonegap-googlemaps-plugin#478]
Greetings,
My app is retrieving information from google.places and displaying it in a little dropdown.  One of the items that is suppose to appear in the prediction list is a little image that is required by google that says "powered by google" and is referred to by a url.  I believe that the plugin modifies the http and converts it to file.  It is possible that cordova or ionic is modifying the dom, but I think that there's a chance that the plugin is doing the modifications, since in windows, this little image appears with no problems.

Here is the logfile that I get from the console. 

GET file://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white2.png net::ERR_FILE_NOT_FOUND googlemaps-cdv-plugin.js:1893
getDivSize googlemaps-cdv-plugin.js:1893
_append_child googlemaps-cdv-plugin.js:583
(anonymous function) jquery-2.1.3.min.js:3
n.fn.extend.domManip jquery-2.1.3.min.js:3
n.fn.extend.after jquery-2.1.3.min.js:3
enter ionic.bundle.js:12954
enter ionic.bundle.js:35378
(anonymous function) ionic.bundle.js:30240
publicLinkFn ionic.bundle.js:15239
boundTranscludeFn ionic.bundle.js:15379
controllersBoundTransclude ionic.bundle.js:16039
ngIfWatchAction ionic.bundle.js:30231
Scope.$digest ionic.bundle.js:22526
Scope.$apply ionic.bundle.js:22789
(anonymous function) autocomplete.js:217
(anonymous function) VM77:17
(anonymous function) VM77:16
(anonymous function) VM73:42
(anonymous function) VM73:24
(anonymous function) VM73:42
d VM73:37
(anonymous function)

If it is the plugin, is it possible to keep it from doing this modification?

**Comment by wf9a5m75** [comment]
I don't support any kind of hacking, and also don't support any specific JS framework.

**Comment by Hirbod** [comment]
No, ne problem is the CSS, and that google delivers the URLS with 

```css
background: url(//maps....)
```
Normally, // would be automatically transformed to http:// or https://, here, on cordova, it get transformed to file://

I'm also using the Google Places Autocomplete and I've fixed it that way:

```CSS

/* google places */

.pac-container::after {
  background-image:url(https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white2.png);
}

.hdpi.pac-container::after {
  background-image:url(https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white2_hdpi.png)
}

.pac-container {
  border: none !important;
}

.pac-icon {
  background-image: url(https://maps.gstatic.com/mapfiles/api-3/images/autocomplete-icons.png) !important;
}

.hdpi .pac-icon {
  background-image: url(https://maps.gstatic.com/mapfiles/api-3/images/autocomplete-icons_hdpi.png) !important;
}
```
